//LOGIN AND COMMAN (auth)
export const SET_LOGIN_FLAG="SET_LOGIN_FLAG";
export const SET_USER_DATA="SET_USER_DATA";
export const SET_USER_AUTHTOKEN="SET_USER_AUTHTOKEN";
export const SET_ROUTE_NAME="SET_ROUTE_NAME";
export const SET_SEARCH_TEXT="SET_SEARCH_TEXT";
export const SET_SEARCH_LOADER="SET_SEARCH_LOADER";


