//LOGIN AND COMMAN (auth)
export const SET_LOGIN_FLAG = "SET_LOGIN_FLAG";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_AUTHTOKEN = "SET_USER_AUTHTOKEN";
export const SET_ROUTE_NAME = "SET_ROUTE_NAME";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
export const SET_SEARCH_LOADER = "SET_SEARCH_LOADER";
export const USER_LOGOUT = "USER_LOGOUT";

// REPORT DESK HOME AUTOCOMPLETE SEARCH
export const SET_AUTOCOMPLETE_OPTIONS = "SET_AUTOCOMPLETE_OPTIONS";
export const SET_BROWSE_DATA = "SET_BROWSE_DATA";
export const SET_SEARCH_REPORT_LIST_DATA = "SET_SEARCH_REPORT_LIST_DATA";

// REPORT DESK HOME PDF LIST & REPORT LIST
export const SET_REPORT_PDF = "SET_REPORT_PDF";
export const SET_REPORT_LIST = "SET_REPORT_LIST";

// REPORT DESK REPORT PAGE INFINITESCROLL
export const SET_MY_REPORT_LIST_DATA = "SET_MY_REPORT_LIST_DATA";
export const SET_MORE_MY_REPORT_LIST_DATA = "SET_MORE_MY_REPORT_LIST_DATA";
export const FETCH_DATA_API_CALL_INITIATED = "FETCH_DATA_API_CALL_INITIATED";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const SET_CATEGORIES = "SET_CATEGORIES";

// REPORT DESK SEARCH REPORT BY CATEGORY ID
export const SET_REPORT_BY_CATEGORY_ID = "SET_REPORT_BY_CATEGORY_ID";
export const SET_SIMILAR_REPORTS = "SET_SIMILAR_REPORTS";
export const SET_CATEGORY_SUBCATEGORY_DATA = "SET_CATEGORY_SUBCATEGORY_DATA";

// REPORT DESK USERS DOWNLOADED REPORT LIST
export const SET_USERS_DOWNLOADED_REPORT = "SET_USERS_DOWNLOADED_REPORT";
export const SET_MORE_DOWNLOADED_REPORT_LIST_DATA =
  "SET_MORE_DOWNLODED_REPORT_LIST_DATA";
export const DOWNLOAD_API_SUCCESS = "DOWNLOAD_API_SUCCESS";
export const DOWNLOAD_API_ERROR = "DOWNLOAD_API_ERROR";
export const DOWNLOADED_REPORT_COUNT = "DOWNLOADED_REPORT_COUNT"; 
